name: crystal_ball
description: A game made with Flame
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  audioplayers: ^5.2.1
  binarize: ^1.5.0
  bloc: ^8.1.2
  equatable: ^2.0.5
  flame: 1.17.0
  flame_audio: ^2.10.1
  flame_bloc: ^1.10.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  flutter_shaders: ^0.1.2
  google_fonts: ^6.1.0
  hydrated_bloc: ^9.1.5
  intl: ^0.18.0
  mockingjay: ^0.4.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/licenses/macondo/
    - google_fonts/
  shaders:
    - shaders/platforms.glsl
    - shaders/the_ball.glsl
    - shaders/mesh_25_gradient.glsl
    - shaders/ground.glsl
    - shaders/rocks.glsl
    - shaders/fog.glsl
